const express = require("express");
const auth = require("../Controller/auth");
const add = require("../Controller/add");
const addImage = require("../Controller/addImage");
const deleteImage = require("../Controller/deleteImage");
const deleteData = require("../Controller/deleteData");
const exploreController = require("../Controller/exploreController");
const loginController = require("../Controller/loginController");
const cardsController = require("../Controller/cardsController");
const applicant = require("../Controller/applicant");
const upload = require("../middleWare/multer");
const save = require("../Controller/save");
const join = require("../Controller/service");
const getFeedback = require("../Controller/getFeedback");
const feedbackForm = require("../Controller/feedbackForm");
const feedback = require("../Controller/feedback");
const { verifyJWT } = require("../middleWare/checkToken");
const editImage = require("../Controller/editImage");
const saveImage = require("../Controller/saveImage");
const moreFeedback = require("../Controller/moreFeedback");
const replyUser = require("../Controller/replyUser");
const getReply = require("../Controller/getReply");
const getComment = require("../Controller/getComment");
const doctorFeedback = require("../Controller/doctorFeedback");
const jobResume = require("../Controller/jobResume");
const resumeUpload = require("../middleWare/verifyResume");
const viewPdf = require("../Controller/viewPdf");
const router = express.Router();
router.post("/SignUp", auth.signUp);
router.post("/login", loginController.login);
// router.get("/details", verifyJWT, exploreController.exploreHome);
router.get("/details", exploreController.exploreHome);
router.get("/eachData", exploreController.fetchOneData);
router.post("/saveChanges", save.saveTable);
// router.get("/cards", verifyJWT, cardsController.cardsControl);
router.get("/cards", cardsController.cardsControl);
// router.get("/exploreService", verifyJWT, join.service);
router.get("/exploreService", join.service);
router.post("/add", add.addData);
router.get("/delete", deleteData.deleteRowData);
router.get("/deleteImage", deleteImage.deleteImageRow);
router.post("/addImage", upload, addImage.addNewImage);
router.get("/eachImage", upload, editImage.EditOneImage);
router.post("/saveImage", upload, saveImage.saveTableImage);
router.post("/feedback", feedbackForm.feedbackFormData);
router.get("/getFeedback", feedback.feedbackControl);
router.post("/addmore", moreFeedback.addfeedData);
// router.get("/moreFeedback", getFeedback.fetchFeedback);
router.post("/reply", replyUser.replyUserReview);
router.get("/doctorFeedback", doctorFeedback.feedback);
router.get("/AllReply", getReply.userReply);
router.post("/resume", resumeUpload, jobResume.resumeEntry);
router.get("/career", resumeUpload, applicant.applicantData);
router.get("/viewFile", viewPdf.ResumeEachImage);
module.exports = router;
